# STARE

Source to Target Automatic Rotating Estimation (STARE) is a publicly available, blood-free quantification approach for PET tracers with irreversible kinetics. See the [preprint](https://biorxiv.org/content/10.1101/2021.09.15.460504v1.full) or [publication](https://doi.org/10.1016/j.neuroimage.2022.118901) for more details. This repository is the python implementation of it. This notebook is an example of its use.

In [1]:
""" Preliminaries, for developing and debugging in a python notebook.
    None of this is strictly necessary, but is useful for development.
"""

# Set up the path so our code is accessible w/o installing from pypi.
import sys, os
if os.path.abspath("..") not in sys.path:
    sys.path.insert(0, os.path.abspath(".."))

# Force automatic re-load of libraries on every call
# (useful for accelerated debugging of oft-changed library code)
%load_ext autoreload
%autoreload 2

print(f"Executing notebook from '{os.getcwd()}'")

Executing notebook from '/home/mike/Projects/pystarepet/examples'

In [11]:
""" Inputs
"""

import pathlib
import pandas as pd


# Base input data
in_path = pathlib.Path("/home/mike/stare_data/sampleData")
subject_id = "NHFDG002"

# Load timing numbers and label this Series as "t"
mid_times_file = in_path / subject_id / f"{subject_id}.raw.midtime.txt"
time_data = pd.read_csv(mid_times_file, header=None, index_col=None)
time_data.columns = ["t", ]

# Find images for each time point
input_data_path = in_path / subject_id / "moco"
time_data["image"] = sorted([str(img) for img in input_data_path.glob(f"{subject_id}.*.MCFI.img")])
time_data["header"] = [str(img).replace(".img", ".hdr") for img in time_data["image"]]

for row in [0, 1, "...", len(time_data)-2, len(time_data)-1]:
    if row == "...":
        print(row)
    else:
        print("@t={:0.3f}: hdr={}, img={}".format(
            time_data.loc[row, "t"],
            time_data.loc[row, 'header'].split("/")[-1],
            time_data.loc[row, 'image'].split("/")[-1],
        ))

@t=0.125: hdr=NHFDG002.01.MCFI.hdr, img=NHFDG002.01.MCFI.img
@t=0.375: hdr=NHFDG002.02.MCFI.hdr, img=NHFDG002.02.MCFI.img
...
@t=45.000: hdr=NHFDG002.25.MCFI.hdr, img=NHFDG002.25.MCFI.img
@t=55.000: hdr=NHFDG002.26.MCFI.hdr, img=NHFDG002.26.MCFI.img

In [12]:
time_data.sample(4)

,t,image,header
4,1.125,/home/mike/stare_data/sampleData/NHFDG002/moco...,/home/mike/stare_data/sampleData/NHFDG002/moco...
18,9.500,/home/mike/stare_data/sampleData/NHFDG002/moco...,/home/mike/stare_data/sampleData/NHFDG002/moco...
20,17.500,/home/mike/stare_data/sampleData/NHFDG002/moco...,/home/mike/stare_data/sampleData/NHFDG002/moco...
1,0.375,/home/mike/stare_data/sampleData/NHFDG002/moco...,/home/mike/stare_data/sampleData/NHFDG002/moco...

In [14]:
# Load tacs numbers
tacs_file = in_path / subject_id / f"{subject_id}.TACs"
df_tacs = pd.read_csv(tacs_file, header=0, index_col=None, sep='\t')
df_tacs

,MidTime,cerfullc_c,cinr_r,pfcl_l,pfcr_r,pipl_l,pipr_r,cinl_l,parl_l,parr_r,...,gcircs_c,cerfullcs_c,hipl_l,hipr_r,cin,hip,par,pcn,pfc,pip
0,0.125,0.001219,0.000025,0.000437,0.001262,0.002146,0.002407,0.000958,0.000952,0.000821,...,0.000096,0.001082,0.000994,0.001990,0.000491,0.001492,0.000887,0.000509,0.000850,0.002276
1,0.375,0.000589,0.003880,0.001482,0.002299,0.001349,0.000853,0.000851,0.001545,0.000893,...,0.000787,0.001167,0.004580,0.002373,0.002366,0.003477,0.001219,0.001535,0.001891,0.001101
2,0.625,0.022178,0.021458,0.019049,0.019636,0.020974,0.024984,0.031402,0.021735,0.021096,...,0.018048,0.021654,0.019885,0.021534,0.026430,0.020710,0.021415,0.020786,0.019342,0.022979
3,0.875,0.065896,0.054349,0.059903,0.062334,0.051660,0.068476,0.069804,0.059352,0.057218,...,0.048731,0.066733,0.072081,0.064423,0.062076,0.068252,0.058285,0.065872,0.061118,0.060068
4,1.125,0.105287,0.077814,0.087844,0.087331,0.081134,0.087697,0.101685,0.091817,0.089255,...,0.093518,0.105841,0.101243,0.095932,0.089750,0.098588,0.090536,0.095227,0.087587,0.084416
5,1.375,0.125409,0.083804,0.106693,0.099249,0.105902,0.103579,0.115707,0.102087,0.102574,...,0.097591,0.120140,0.085125,0.088871,0.099756,0.086998,0.102330,0.107754,0.102971,0.104741
6,1.625,0.129880,0.106786,0.111563,0.108825,0.101996,0.101189,0.092756,0.114690,0.113449,...,0.127700,0.127790,0.117475,0.092421,0.099771,0.104948,0.114070,0.116796,0.110194,0.101592
7,1.875,0.133668,0.105820,0.126444,0.109873,0.122822,0.098220,0.108074,0.120471,0.124852,...,0.122860,0.132344,0.100262,0.101986,0.106947,0.101124,0.122662,0.143024,0.118159,0.110521
8,2.250,0.136150,0.119279,0.132019,0.133018,0.116210,0.105676,0.123670,0.132873,0.131268,...,0.138279,0.131453,0.117198,0.121995,0.121475,0.119596,0.132071,0.148836,0.132519,0.110943
9,2.750,0.160165,0.119490,0.144573,0.143370,0.125595,0.124995,0.140819,0.149042,0.145464,...,0.162653,0.154188,0.125031,0.117951,0.130154,0.121491,0.147253,0.157012,0.143972,0.125295
10,3.250,0.173280,0.140589,0.154807,0.153237,0.145093,0.138892,0.146595,0.166587,0.158726,...,0.181314,0.167721,0.133098,0.131948,0.143592,0.132523,0.162656,0.178745,0.154022,0.141992
11,3.750,0.169721,0.147439,0.169162,0.169573,0.130734,0.145851,0.159601,0.171805,0.171354,...,0.183131,0.165146,0.134195,0.141163,0.153520,0.137679,0.171579,0.184949,0.169367,0.138293
12,4.250,0.182489,0.178147,0.179759,0.172835,0.153641,0.147042,0.178785,0.189447,0.177511,...,0.191595,0.175074,0.138466,0.145937,0.178466,0.142201,0.183479,0.212995,0.176297,0.150342
13,4.750,0.191760,0.178207,0.186229,0.182285,0.154547,0.165948,0.176638,0.196019,0.188412,...,0.208405,0.185313,0.141671,0.152208,0.177422,0.146939,0.192215,0.213829,0.184257,0.160247
14,5.500,0.200702,0.173551,0.197715,0.196259,0.159607,0.165090,0.177771,0.206111,0.207248,...,0.213463,0.195270,0.158214,0.168684,0.175661,0.163449,0.206680,0.228004,0.196987,0.162349
15,6.500,0.200097,0.198360,0.209702,0.209529,0.177089,0.185458,0.202007,0.223068,0.220976,...,0.215222,0.195352,0.187342,0.175402,0.200183,0.181372,0.222022,0.240349,0.209616,0.181274
16,7.500,0.217708,0.215359,0.231723,0.226156,0.171856,0.179010,0.210537,0.238375,0.239059,...,0.235414,0.212025,0.175923,0.173574,0.212948,0.174749,0.238717,0.259372,0.228939,0.175433
17,8.500,0.231441,0.223835,0.241220,0.238429,0.187581,0.197291,0.226678,0.255217,0.252206,...,0.256420,0.224761,0.189741,0.182654,0.225257,0.186197,0.253711,0.269992,0.239824,0.192436
18,9.500,0.238336,0.225220,0.256739,0.246465,0.204332,0.202126,0.247720,0.269251,0.265760,...,0.250911,0.231465,0.187996,0.202552,0.236470,0.195274,0.267505,0.288722,0.251602,0.203229
19,12.500,0.266564,0.271694,0.294872,0.293643,0.228431,0.233574,0.268060,0.308058,0.303615,...,0.280142,0.257880,0.219158,0.230110,0.269877,0.224634,0.305837,0.329382,0.294258,0.231002
20,17.500,0.293292,0.311108,0.345030,0.344578,0.269579,0.265307,0.322896,0.364977,0.360525,...,0.320919,0.285443,0.252505,0.252779,0.317002,0.252642,0.362751,0.395798,0.344804,0.267443
21,22.500,0.328640,0.355640,0.393906,0.388372,0.292134,0.298243,0.367204,0.411985,0.407808,...,0.360026,0.319125,0.278746,0.284653,0.361422,0.281699,0.409897,0.444053,0.391139,0.295189
22,27.500,0.355768,0.392347,0.438202,0.430832,0.332948,0.326590,0.396036,0.456520,0.450511,...,0.385900,0.345388,0.306107,0.315271,0.394191,0.310689,0.453516,0.496138,0.434517,0.329769
23,35.000,0.386412,0.442082,0.492806,0.484387,0.364809,0.371180,0.442626,0.513557,0.505783,...,0.420615,0.375803,0.341745,0.350418,0.442354,0.346081,0.509670,0.560033,0.488596,0.367995
24,45.000,0.425978,0.499556,0.545442,0.534020,0.404456,0.405021,0.503023,0.576548,0.565648,...,0.464655,0.414690,0.380663,0.379331,0.501290,0.379997,0.571098,0.624300,0.539731,0.404739
25,55.000,0.461306,0.543852,0.597402,0.583756,0.446605,0.443787,0.555515,0.631409,0.617366,...,0.504989,0.447990,0.409937,0.419344,0.549684,0.414641,0.624387,0.681207,0.590579,0.445196

## Equations

### 1

The standard 2 tissue irreversible compartment model (2TCirr) (manuscript eq 1)

$$C_T(t)=K_1({IRF}\otimes{C_p})=K_1[(\frac{k_2}{k_2+k_3}e^{-(k_2+k_3)t} + \frac{k_3}{k_2+k_3})\otimes{C_p}](t)$$

where $t$ is time

where ${IRF}$ is the impulse response function for the target region

where $k_1$, $k_2$, $k_3$ are the microparameters of the 2TCirr model for the target region

### 2

Using equation 1 for both "source" and "target" compartments.

$$C_T(t)=K_{1,T}({IRF}_T\otimes{C_p})=K_{1,T}[(\frac{k_{2,T}}{k_{2,T}+k_{3,T}}e^{-(k_{2,T}+k_{3,T})t} + \frac{k_{3,T}}{k_{2,T}+k_{3,T}})\otimes{C_p}](t)$$

$$C_S(t)=K_{1,S}({IRF}_S\otimes{C_p})=K_{1,S}[(\frac{k_{2,S}}{k_{2,S}+k_{3,S}}e^{-(k_{2,S}+k_{3,S})t} + \frac{k_{3,S}}{k_{2,S}+k_{3,S}})\otimes{C_p}](t)$$

### 3

Define the source-to-target tissue model using a LaPlace transform to express each target compartment's TAC

$$f_T(t,\theta_{T,S})=\frac{K_{1,T}}{K_{1,S}}C_s(t) + \frac{K_{1,T}}{K_{1,S}}C_s(t)\otimes(L_{T,S}e^{{v_{T,S}}^t}+M_{T,S}e^{{\epsilon_{T,S}}^t})$$

where t is time, $\otimes$ denotes convolution, and $\theta_{T,S}$ comprises the macro-parameters $L_{T,S}$, $M_{T,S}$, $v_{T,S}$, and $\epsilon_{T,S}$.

Just checking: $\sigma\epsilon\omega\pi$ $\Sigma\Omega\Pi$

### 4

Sum the square of the residuals to determine goodness of fit.

$$\phi(t_m,\theta_{T,S})=\sum_{T=1}^{n}\sum_{m=1}^{n}w_m(C_T(t_m)-f_T(t_m,\theta_{T,S}))^2$$

where $w$ represents a set of known weights for PET frame durations.

### 5

To equation 4, add a term anchoring the estimate to PET-derived measures of vascular activity.

$$\phi(t_m,\theta_{T,S})=\sum_{T=1}^{n}\sum_{m=1}^{n}w_m(C_T(t_m)-f_T(t_m,\theta_{T,S}))^2 + \lambda\sum_{T=1}^N\lvert{K_{i,T}-K_{i,vasc,T}}\rvert$$

This is the final cost function used to fit the model.

### Altogether

From the manuscript, Figure 1

![Manuscript Figure 1](bartlett_2021_stare_figure1.jpg "Figure 1")

In [2]:
from src.util import f

f("Working")

Working